const products = [{
        id: 1,
        img: "img/products/lactal-blanco.jpg",
        name: "Pan Lactal Blanco",
        info: "Paquete de 350gr cortado en rodajas",
        price: 200,
        category: "panes",
    },
    {
        id: 2,
        img: "img/products/receta-de-pan-de-cereales-1.jpg",
        name: "Pan de Salvado",
        info: "Paquete de 350gr cortado en rodajas",
        price: 220,
        category: "panes",
    },
    {
        id: 3,
        img: "img/products/pan-integral-semillas.jpg",
        name: "Pan Integral con Semillas",
        info: "Paquete de 350gr cortado en rodajas",
        price: 250,
        category: "panes",
    },
    {
        id: 4,
        img: "img/products/mignon.jpg",
        name: "Mignoncitos",
        info: "Paquete de 250gr",
        price: 55,
        category: "panes",
    },
    {
        id: 5,
        img: "img/products/pan-flauta-fondo.jpg",
        name: "Flautas",
        info: "Paquete de 250gr",
        price: 55,
        category: "panes",
    },
    {
        id: 6,
        img: "img/products/pan-baguette.jpg",
        name: "Baguette",
        info: "1 unidad por bolsa",
        price: 120,
        category: "panes",
    },
    {
        id: 7,
        img: "img/products/pan-leche-blanco.jpg",
        name: "Pan de leche",
        info: "paquete x unidad",
        price: 60,
        category: "panes",
    },
    {
        id: 8,
        img: "img/products/croissant.jpg",
        name: "Croissant",
        info: "venta por unidad",
        price: 90,
        category: "facturas",
    },
    {
        id: 9,
        img: "img/products/factura-crema.jpg",
        name: "Crema pastelera",
        info: "venta por unidad",
        price: 50,
        category: "facturas",
    },
    {
        id: 10,
        img: "img/products/factura-ddl.jpg",
        name: "Dulce de Leche",
        info: "venta por unidad",
        price: 50,
        category: "facturas",
    },
    {
        id: 11,
        img: "img/products/grasa.jpeg",
        name: "Medialuna de Grasa",
        info: "venta por unidad",
        price: 50,
        category: "facturas",
    },
    {
        id: 12,
        img: "img/products/manteca.jpg",
        name: "Medialuna de Manteca",
        info: "venta por unidad",
        price: 50,
        category: "facturas",
    },
    {
        id: 13,
        img: "img/products/pastelera-y-membrillo.jpg",
        name: "Pastelera y membrillo",
        info: "venta por unidad",
        price: 50,
        category: "facturas",
    },
    {
        id: 14,
        img: "img/products/figacitas-crudoylechuga.jpg",
        name: "Sandwich Jamon crudo y lechuga",
        info: "bandeja de 2 unidades",
        price: 300,
        category: "sandwichs",
    },
    {
        id: 15,
        img: "img/products/figacitas-jyq.jpg",
        name: "Sandwich Jamon y Queso",
        info: "bandeja de 2 unidades",
        price: 260,
        category: "sandwichs",
    },
    {
        id: 16,
        img: "img/products/figacitas-tomateyqueso.jpg",
        name: "Sandwich Tomate y Queso",
        info: "bandeja de 2 unidades",
        price: 240,
        category: "sandwichs",
    },
    {
        id: 17,
        img: "img/products/bizcochitograsa.jpeg",
        name: "Bizcochitos de grasa",
        info: "Bolsa de 250gr",
        price: 150,
        category: "grasa",
    },
    {
        id: 18,
        img: "img/products/cremona.jpeg",
        name: "Cremona",
        info: "Venta por unidad",
        price: 300,
        category: "grasa",
    },
    {
        id: 19,
        img: "img/products/barrasgranola.jpg",
        name: "Barras de Cereal",
        info: "paquete x 6 unidades",
        price: 320,
        category: "barras de cereal",
    },
]


export { products };